### ISSUE TITLE
✨ [Feature] Use Dependabot to auto update packages and actions

### ISSUE THREAD

**Issue by DevHaoZi** [goravel/goravel#140]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

Use Dependabot to auto update packages and actions.

`dependabot.yml` can be like:

```
# https://docs.github.com/zh/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
```
