### ISSUE TITLE
✨ [Feature] add govulncheck actions to framework workflow

### ISSUE THREAD

**Issue by devhaozi** [goravel/goravel#480]
### Before feedback (在反馈之前)

- [X] There are no features that I want to submit in Issues (当前 Issues 中没有我将要提交的新功能)

### Describe Feature (描述功能)

```
name: Run govulncheck

on:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  govulncheck-check:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: false

      - name: Install Govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run Govulncheck
        run: govulncheck ./...
```

Is every 6 hours appropriate? If it is too frequent, we can adjust it appropriately.
